config/routes.rb
Encrypt::Application.routes.draw do
  devise_for :users
  root :to => 'messages#index'

  resources :messages do
    member do
      get 'show_encrypted'
      get 'sent'
    end
  end

   match 'sent' => 'messages#sent', :as => 'sent'


end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :title, :user_id, :user
  after_create :encrypt!


  def before_save(record)
    record.credit_card_number = encrypt(record.credit_card_number)
  end

  private
  def encrypt! 
	require 'digest/sha1'
	cipher = Gibberish::AES.new(Digest::SHA1.hexdigest(user.encrypted_password))
	self.content = cipher.enc(content)
	save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :current
  # attr_accessible :title, :body
  def to_s
  	email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def sent

    @messages = Message.where 'created_by = ?', current_user.id

    render  'index.html.erb'
    
  end
  def index
    @messages = Message.where 'user_id = ?', current_user.id

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show_encrypted
    @message = Message.find params[:id]
    if current_user.id == @message.user_id
      cipher = Gibberish::AES.new(Digest::SHA1.hexdigest(current_user.encrypted_password))
      @message_dec = cipher.dec(@message.content)
      respond_to do |format|
        format.html # show_encrypted.html.erb
        format.json { render json: @message }
       end 
    else
      flash[:error] = "You can't show this message..."
      redirect_to  messages_path
    end
  end

  def show
    @message = Message.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @message.created_by = current_user.id
    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Encrypt" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Encrypt</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Received messages", messages_path  %></li>
              <li><%= link_to "Sent messages", sent_path  %></li>
              <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title %>
  <%= f.association :user %>
  <%= f.text_area :content %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.title %></td>
    <td><%= message.user %></td>

    <td><%= link_to 'Show encrypted', show_encrypted_message_path(message), :class => 'btn btn-success'  if current_user.id == message.user.id%></td>

    <td><%= link_to 'Show', message ,:class => 'btn'%></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } , :class =>'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path ,:class => 'btn btn-success'%>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @message.title %>
</p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>

<p>
  <b>User:</b>
  <%= @message.user %>
</p>
<p>
	<b>Link to sharing:</b>
	<%= url_for(show_encrypted_message_url)  %>
</p>	

<%= link_to 'Back', messages_path, :class => 'btn btn-success' %>

app/views/messages/show_encrypted.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @message.title %>
</p>

<p>
  <b>Content:</b>
  <%= @message_dec %>
</p>

<p>
  <b>User:</b>
  <%= @message.user %>
</p>

<%= link_to 'Back', messages_path %>